- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: "mv target/{{component}}-{{shipping_version}}.jar {{component}}.jar"
  args:
    chdir: /app

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

